@echo off

echo 安装所需的Python包...
echo 安装Flask...
pip install Flask 2.3.2
echo 安装Flask-Cors...
pip install Flask-Cors 3.0.10
echo 安装psutil...
pip install psutil 5.9.5
echo 安装netifaces...
pip install netifaces 0.11.0
echo 安装本地netifaces...
pip install ./atart/netifaces-0.11.0-cp312-cp312-win_amd64.whl
echo 安装Flask-Session...
pip install Flask-Session 0.5.0
echo 安装python-dotenv...
pip install python-dotenv 1.0.0
echo 安装Werkzeug...
pip install Werkzeug 2.3.7
echo 安装Jinja2...
pip install Jinja2 3.1.2
echo 安装chardet...
pip install chardet 5.2.0
echo 安装requests...
pip install requests 2.32.4
echo 安装gevent...
pip install gevent 23.9.1
echo 安装pdfminer.six...
pip install pdfminer.six
echo 安装Pillow...
pip install Pillow 10.4.0
echo 安装PyPDF...
pip install PyPDF 6.0.0
echo 安装urllib3...
pip install urllib3 2.2.1